### ISSUE TITLE
[EPIC] Build homepage

### ISSUE THREAD

**Issue by theresaanna** [qbitkit/qbitkit-site#1]
- [ ] Design homepage
- [ ] Set up GatsbyJS scaffolding
- [ ] Create and style header and footer components
- [ ] Write copy for body
- [ ] Create and style body components

**Comment by theresaanna** [comment]
Here are the mock ups for the homepage.

![97CEB732-F859-47A3-A198-CB3FE4B9BEB5](https://user-images.githubusercontent.com/126935/116770562-c3b06400-a9f9-11eb-86db-322b450efc3d.png)
![7456EE3F-8B48-40DA-A460-2AEB9C8F40AF](https://user-images.githubusercontent.com/126935/116770565-c57a2780-a9f9-11eb-80fc-7d136b1306f0.png)
![126D15C2-1E58-4EE4-86A3-58747E6628D4](https://user-images.githubusercontent.com/126935/116770567-c612be00-a9f9-11eb-9daa-e00e5e7ae862.png)
