### ISSUE TITLE
[EPIC] Infrastructure 

### ISSUE THREAD

**Issue by theresaanna** [qbitkit/qbitkit-site#6]
- [ ] Get domain pointing to the right place
- [ ] Setup info@qbitkit.org
- [ ] Setup continuous integration
